version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pricetrack-painel
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - pricetrack-network

networks:
  pricetrack-network:
    driver: bridge